CREATE DATABASE IF NOT EXISTS shopflow_user;
CREATE DATABASE IF NOT EXISTS shopflow_product;
CREATE DATABASE IF NOT EXISTS shopflow_cart;
CREATE DATABASE IF NOT EXISTS shopflow_order;
CREATE DATABASE IF NOT EXISTS shopflow_coupon;
CREATE DATABASE IF NOT EXISTS shopflow_payment;